--create new TYPE called grocery
--The grocery TYPE should be an ENUM that can be one of the following possible values: Main, Snack, Lunch, Breakfast
--create new TABLE called shopping_list w/ 6 columns (id, name, price(2 decimals), date_added(default to now()), checked(default false), category(use grocery type created))


DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
);
